//! PlantUML emitter.

use std::fmt::Write;

use crate::config::StyleConfig;
use crate::model::{ArrowStyle, Block, BlockKind, FlowEvent, FlowSpec, MessageSpec};

const BANNER: &str =
    "' !!! GENERATED by rust2seq — do not edit; regenerated on `cargo rust2seq` !!!";

pub fn emit_plantuml(flow: &FlowSpec, style: &StyleConfig) -> String {
    let mut out = String::with_capacity(1024);

    // Banner lives INSIDE the @startuml/@enduml block so the whole file is one
    // diagram region — keeps VSCode's PlantUML preview happy regardless of
    // cursor position (it renders the diagram the cursor is currently inside).
    writeln!(out, "@startuml {}", flow.name).unwrap();
    writeln!(out, "{BANNER}").unwrap();

    if let Some(title) = &flow.title {
        writeln!(out, "title {}", escape_inline(title)).unwrap();
    }

    write_skinparams(&mut out, style);

    writeln!(out, "autonumber").unwrap();
    out.push('\n');

    for p in &flow.participants {
        match &p.color {
            Some(c) => writeln!(
                out,
                "participant \"{}\" as {} {}",
                escape_quoted(&p.display),
                p.alias,
                c
            )
            .unwrap(),
            None => writeln!(
                out,
                "participant \"{}\" as {}",
                escape_quoted(&p.display),
                p.alias
            )
            .unwrap(),
        }
    }
    out.push('\n');

    write_events(&mut out, &flow.events, 0);

    out.push('\n');
    writeln!(out, "@enduml").unwrap();
    out
}

fn write_events(out: &mut String, events: &[FlowEvent], depth: usize) {
    for ev in events {
        match ev {
            FlowEvent::Message(m) => write_message(out, m, depth),
            FlowEvent::Block(b) => write_block(out, b, depth),
        }
    }
}

fn write_message(out: &mut String, msg: &MessageSpec, depth: usize) {
    let pad = indent(depth);
    writeln!(
        out,
        "{pad}{} {} {} : {}",
        msg.from,
        arrow_with_color(msg.style, msg.color.as_deref()),
        msg.to,
        escape_inline(&msg.label)
    )
    .unwrap();
    if let Some(note) = &msg.note {
        writeln!(
            out,
            "{pad}note over {}, {}: {}",
            msg.from,
            msg.to,
            escape_inline(note)
        )
        .unwrap();
    }
}

fn write_block(out: &mut String, block: &Block, depth: usize) {
    let pad = indent(depth);
    let keyword = block.kind.keyword();
    for (i, branch) in block.branches.iter().enumerate() {
        let lead = if i == 0 {
            keyword.to_string()
        } else {
            match block.kind {
                BlockKind::Alt => "else".to_string(),
                // `loop`/`opt` are single-branch; defensive fallthrough keeps
                // the same keyword if extra branches ever sneak in.
                BlockKind::Loop | BlockKind::Opt => keyword.to_string(),
            }
        };
        if branch.label.is_empty() {
            writeln!(out, "{pad}{lead}").unwrap();
        } else {
            writeln!(out, "{pad}{lead} {}", escape_inline(&branch.label)).unwrap();
        }
        write_events(out, &branch.events, depth + 1);
    }
    writeln!(out, "{pad}end").unwrap();
}

fn indent(depth: usize) -> String {
    "    ".repeat(depth)
}

/// Insert `[#color]` after the leading `-` of the arrow so the result is
/// PlantUML's `Foo -[#FF0000]> Bar` (or `-[#FF0000]->` for dashed). The
/// color string is expected to include the leading `#` or be a named color.
fn arrow_with_color(style: ArrowStyle, color: Option<&str>) -> String {
    let s = style.as_str();
    match color {
        None => s.to_string(),
        Some(c) => format!("-[{}]{}", c, &s[1..]),
    }
}

fn write_skinparams(out: &mut String, s: &StyleConfig) {
    writeln!(
        out,
        "skinparam shadowing {}",
        if s.shadowing { "true" } else { "false" }
    )
    .unwrap();
    writeln!(out, "skinparam roundCorner {}", s.round_corner).unwrap();
    writeln!(out, "skinparam defaultFontName \"{}\"", s.default_font_name).unwrap();
    writeln!(out, "skinparam defaultFontSize {}", s.default_font_size).unwrap();
    writeln!(
        out,
        "skinparam sequenceArrowThickness {}",
        format_float(s.sequence_arrow_thickness)
    )
    .unwrap();
    writeln!(
        out,
        "skinparam sequenceMessageAlign {}",
        s.sequence_message_align
    )
    .unwrap();
    writeln!(
        out,
        "skinparam responseMessageBelowArrow {}",
        if s.response_message_below_arrow {
            "true"
        } else {
            "false"
        }
    )
    .unwrap();
    writeln!(
        out,
        "skinparam ParticipantPadding {}",
        s.participant_padding
    )
    .unwrap();
    writeln!(out, "skinparam BoxPadding {}", s.box_padding).unwrap();
    out.push('\n');
}

/// Format a float without trailing zeros after the decimal point, keeping at
/// least one digit on each side (`1.4` stays `1.4`, `2.0` becomes `2`).
fn format_float(f: f32) -> String {
    if f.fract() == 0.0 {
        format!("{}", f as i64)
    } else {
        // Trim trailing zeros from a fixed precision representation.
        let s = format!("{:.3}", f);
        s.trim_end_matches('0').trim_end_matches('.').to_string()
    }
}

/// Escape a string for a single PlantUML line (after the colon of an arrow,
/// inside `title`, etc). Newlines in the input become PlantUML's `\n` literal
/// — PlantUML interprets `\n` inside quoted strings AND in message labels as a
/// line break.
fn escape_inline(s: &str) -> String {
    s.replace('\n', "\\n")
}

/// Escape a string going inside double quotes: replace embedded `"` and
/// preserve `\n` line breaks.
fn escape_quoted(s: &str) -> String {
    s.replace('"', "\\\"").replace('\n', "\\n")
}
